// Per-effect shuffle ratings. 0 = never picked by shuffle (still selectable
// by hand). 1 = default. Higher = more likely. Range 0-3.
// Tune here, never in effect files.
export const EFFECT_RATINGS = {
  // image/video
  dataMosh: 1.2,
  pixelSort: 1.2,
  duotone: 1.3,
  waveWarp: 1.1,
  scanline: 1.0,
  hueRotate: 1.2,
  bitFlip: 1.0,
  chanShift: 1.1,
  quantize: 1.0,
  lensAberration: 1.1,
  stripeBurn: 1.0,
  pixelEcho: 1.1,
  matrixColor: 1.2,
  invertZones: 1.0,
  levels: 1.0,
  crystallize: 0.9,
  edgeSketch: 1.1,
  pixelate: 1.1,
  sigil: 1.2,
  displacementMap: 1.3,
  wraith: 1.2,
  anomalousSpasm: 1.0,
  modularMask: 0.9,
  gaussianBlur: 0.9,
  oilPaint: 0.8,
  voronoi: 0.8,
  watercolorBleed: 1.4,
  inkWash: 1.4,
  mangaScreentone: 1.2,
  risograph: 1.4,
  screenPrint: 1.3,
  halftoneFilter: 1.1,
  lowPoly: 1.3,
  mandala: 1.2,
  leadedGlass: 1.2,
  cyanotype: 1.4,
  duotoneGrade: 1.3,
  crossStitch: 1.1,
  trueAscii: 1.0,
  blueprint: 1.3,
  woodcut: 1.2,
  databend: 1.1,
  channelTear: 1.0,
  staticBloom: 1.0,
  ghostTrail: 1.0,
  macroblockRot: 0.9,
  scanlineWarp: 1.0,
  lensWarp: 1.1,
  lineDistortion: 1.0,
  // text
  zalgo: 1.0,
  stutter: 1.0,
  caseChaos: 1.0,
  repeatBlocks: 1.0,
  scramble: 1.0,
  noiseInject: 1.0,
  fontShuffle: 1.0,
  positionDistortion: 1.0,
  segReverse: 1.0,
  lineChaos: 1.0,
  marginDrift: 1.0,
  whitespaceBreathe: 1.0,
  homoglyph: 1.0,
  caseWave: 1.0,
  // audio
  bitCrush: 1.0,
  tapeWobble: 1.0,
  dropout: 1.0,
  granularScatter: 1.0,
  outburst: 1.0,
  feedback: 1.0,
  chunkRepeat: 1.0,
  sampleCrush: 1.0,
  softCompress: 1.0,
  subtleVibrato: 1.0,
};

export function getRating(effectId) {
  return EFFECT_RATINGS[effectId] ?? 1;
}
